name: Web Backend CI Pipeline

on:
  push:
    branches:
      - main
      - budget-app
    paths:
      - 'backend/**'
      - '.github/workflows/backend-test.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-test.yml'

jobs:
  backend-ci:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: "postgresql://dummy:dummy@localhost:5432/dummy"
      SUPABASE_URL: "https://dummy.supabase.co"
      SUPABASE_KEY: "dummy_key"
    defaults:
      run:
        working-directory: ./backend

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        cache-dependency-glob: "backend/uv.lock"

    - name: Set up Python
      run: uv python install

    - name: Install dependencies
      run: uv sync --all-extras --dev

    - name: Run tests with pytest
      run: uv run pytest
